let num1 = Math.floor(Math.random()*90)+10;
let num2 = Math.floor(Math.random()*90)+10;
let num3 = Math.floor(Math.random()*90)+10;
let num4 = Math.floor(Math.random()*90)+10;
let num5 = Math.floor(Math.random()*90)+10;
let sum = num1 + num2 + num3 + num4 + num5;
let avg = sum/5;
console.log("2 digit Random numbers :- " +num1+ ',' +num2+ ',' +num3+ ',' +num4+ ',' +num5);
console.log('Sum of Five Random Numbers = ' +sum);
console.log('Average of Five Random Numbers = ' +avg);